name: Deploy Angular App to HostGator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        run: npm install --force

      - name: Build Angular App
        run: ng build

      - name: Deploy to HostGator
        run: |
          scp -r dist/* luizan96@162.241.203.10:/home2/luizan96/store.luizantonio.dev.br
        env:
          HOSTGATOR_SSH_KEY: ${{ secrets.HOSTGATOR_SSH_KEY }}
