name: Deploy Angular App to HostGator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        run: npm install --force

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Build Angular App
        run: ng build

      - name: Deploy to HostGator
        run: |
         lftp -e "mirror -R -e -x .git -x .github -x node_modules -x .gitignore -x .gitattributes -x README.md -x angular.json -x .editorconfig -x .browserslistrc -x karma.conf.js -x tsconfig.json -x tsconfig.app.json -x tsconfig.spec.json -x e2e -x src -- $GITHUB_WORKSPACE/car-store-front/dist/* /home2/luizan96/store.luizantonio.dev.br" -u luizan96,$HOSTGATOR_FTP_PASSWORD 162.241.203.10
        env:
          HOSTGATOR_FTP_PASSWORD: ${{ secrets.HOSTGATOR_FTP_PASSWORD }}
