name: Deploy Angular App to HostGator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular App
        run: ng build --prod

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy to HostGator
        run: |
          lftp -e "mirror -R --exclude-glob .git --exclude-glob .github --exclude-glob node_modules --exclude-glob .gitignore --exclude-glob .gitattributes --exclude-glob README.md --exclude-glob angular.json --exclude-glob .editorconfig --exclude-glob .browserslistrc --exclude-glob karma.conf.js --exclude-glob tsconfig.json --exclude-glob tsconfig.app.json --exclude-glob tsconfig.spec.json --exclude-glob e2e --exclude-glob src $GITHUB_WORKSPACE/dist /home2/luizan96/store.luizantonio.dev.br" -u luizan96,$HOSTGATOR_FTP_PASSWORD 162.241.203.10
        env:
          HOSTGATOR_FTP_PASSWORD: ${{ secrets.HOSTGATOR_FTP_PASSWORD }}
